### ISSUE TITLE
Change meta tags

### ISSUE THREAD

**Issue by naijwu** [nwplus/external-templates#262]
Completion Criteria
 - [ ] Use appropriate favicon
 - [ ] Add description meta tag
 - [ ] Add open graph preview image 

all in top of `pages/index.jsx` here:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/26179641/204407776-2027dc66-9cba-4ed9-a6ad-6a4231a74ef2.png">
